a = input('Digite Algo:')
print('O tipo primitivo deste valor é',type(a))
print('Só tem espaço ?', a.isspace())
print('É um Numero ?', a.isnumeric())
print('É Alfanumerico ?', a.isalnum())
print('Só tem espaços ?', a.isspace())
print('É Alfabetico ?', a.isalpha())
print('Está em maiuscula ?', a.isupper())
print('Está em minuscula ?', a.islower())
print('Está Capitalizada ?', a.istitle())
