a = input('Digite Algo:')
print('O tipo primitivo deste valor é',type(a))
print('So tem espaço ?', a.isspace())
print('É um Numero?', a.isnumeric())
print('É Alfanumerico ?', a.isalnum())
print('Só tem espaços ?',a.isspace())
print('É Alfabetico ?', a.isalpha())
print('Esta em  maiuscula ?',a.isupper())
print('Esta em minuscula ?', a.islower())
print('Esta Capitalizada ?',a.istitle())